### ISSUE TITLE
x86 installer detected as malware by Avast due to lack of compliance with Avast clean software policy

### ISSUE THREAD

**Issue by steel9** [AndyFul/Hard_Configurator#1]
Reply from false positive report:
"

Hello,

Thank you for reporting this.

Our virus specialists have confirmed that this detection is indeed correct due to lack of compliance with our clean software policy.

You can find further details in the following article: [Avast Clean Guidelines](https://www.avast.com/faq.php?article=AVKB228).

With regards,

Avast Customer Care

"

**Comment by AndyFul** [comment]
Thanks. Solved with ver. 4.0.0.0.

**Comment by AndyFul** [comment]
All versions of H_C (from the ve. 4.0.1.0) are whitelisted by Avast before they are publicly available.
