### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Cutechri** [AndyFul/Hard_Configurator#10]
This software is really great, I use it daily, and I've also recommended it wholeheartedly in my security guide on my website.

However, a feature that could really improve this software is a GUI for managing the shell extensions (after enabling Shell Extension Security), kind of like the SRP whitelist GUI.

It'd be nice if it would list all existing Shell Extensions, and an option to move them in or out of the Approved list. It's kind of tedious to do it manually, and this would entice more people to use that feature.

**Comment by AndyFul** [comment]
Did you have any problem with the setting <Shell Extension Security>? 
Did it block some shell extensions?

**Comment by CuteCry** [comment]
It interfered with Bandizip.

**Comment by AndyFul** [comment]
Are you sure? I installed Bandizip on Windows 10 and it did not add any shell extension to the keys:
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved

Despite this and the fact that I use EnforceShellExtensionSecurity restriction, I have several functional Bandizip shell extensions (right-click Explorer menu):
5 entries for packed zip file
4 entries for unpacked file

Your post directed my attention to the EnforceShellExtensionSecurity policy. 
I tested it on Windows 10, 7, Vista, and XP. The policy works well on Windows XP. I installed 7-ZIP which during the installation creates CLSID under the key:
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
After removing this CLSID the 7-ZIP shell extension disappears from the Explorer context menu.
But, doing the same on Windows 10, 7, and Vista did not change anything. I could still use the 7-ZIP extension even after removing CLSID (and restarting the computer).

Could you confirm if renaming the CLSID of Bandizip shell extension under the key:
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
and restarting the computer, can have any impact on the functionality of the Bandizip entries on the Explorer context menu?

**Comment by AndyFul** [comment]
I made some extensive research and found this:

ID | 0x00100000
Symbolic Name : REST_ENFORCESHELLEXTSECURITY
Key : Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
Value : EnforceShellExtensionSecurity
Availability : version 4.0 (NT only) to 6.0

https://www.geoffchappell.com/studies/windows/shell/shell32/api/util/restrictions.htm

In Microsoft ADMX resources the policy EnforceShellExtensionSecurity should work for Windows NT 4.0 and later versions. But from the above website, it follows that it probably works only up to Windows NT 6.0 (Windows Vista).

**Comment by CuteCry** [comment]
So does that mean the H_C feature does nothing in 10 and 11?

**Comment by AndyFul** [comment]
The Microsoft ADMX settings and many reliable resources on the web recommend this policy. My quick test cannot disproof this. It would be helpful if others could test this policy to confirm my results. The test is very simple:

1. Use the Nirsoft tool ShexView to identify running shell extensions.
2. Rename the CLSID of the extension visible under the registry key:
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
and also under the key (if the extension is present here):
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved
3. Log off/log in.
4. Use ShexView to see if the extension has been blocked.
5. Restore the original name of CLSID

I found one user who asked Microsoft about this issue. He got the answer that some extensions may be not blocked, but generally the policy should work.

**Comment by CuteCry** [comment]
Got it. Still, my original feature request would be a nice implementation and I'd find it easier to recommend enabling this to people in my guide.

**Comment by AndyFul** [comment]
As you can see, this policy is not included in the H_C Recommended_Settings. 
Why do you want to recommend it? Are you sure that it works on your computer?
