### ISSUE TITLE
Default deny mode causes executables to not function on the built-in administrator account

### ISSUE THREAD

**Issue by RabbyDevs** [AndyFul/Hard_Configurator#11]
Edition	Windows 11 Pro **Insider Preview**
Version	22H2
OS build	25131.1000
Experience	Windows Feature Experience Pack 1000.25131.1000.0
![image](https://user-images.githubusercontent.com/67389402/172671169-cf158663-99c2-440b-aadf-4dfadeb22a7b.png)
I personally have no idea what could be causing this, even when disabling a specific policy which could be causing this (User Account Control: Admin Approval Mode for the built-in administrator account), nothing executes. Just says that I don't have permission on the built-in administrator account (the only administrator account on my system right now).

**Comment by AndyFul** [comment]
If this block happens when you use a shortcut, then check the path in the target area used by the shortcut to run SwitchDefaultDeny.exe.
