### ISSUE TITLE
Whitelist by path

### ISSUE THREAD

**Issue by sirrus** [AndyFul/Hard_Configurator#2]
There is an issue when I try to edit existing entries with the same name. They show up only once.

This can happen when you're trying to move form Restric'tor to H_C...

And edtiting (e.g. change name) inside the Whitelist would be great...

**Comment by AndyFul** [comment]
How do you add the entries with the same name? Normally, you should add the new file paths via the options: Add File, Add Folder, or AddPath*Wildcards. Then you will see the whitelisted entries as file/folder paths. You can edit the entry via the option Edit Info. Please note, that after doing it, the real path remains untouched - only the entry name will be different. 

Example.
When you whitelist the file path: c:\z\eso.exe you will see the entry:
c:\z\eso.exe (***) www.sordum.org Easy Services Optimizer 1.2.0.0 REG=HKLM ...
After editing you can see for example:
My favorite  ESO from sordum.org  REG=HKLM ...
But still the path c:\z\eso  will be whitelisted.

**Comment by sirrus** [comment]
I'm trying to migrate from Restric'tor to H_C - Restric'tor (maybe this should not be like this) creates entries without or even with the same name...

> Hi sirrus,
> How do you add the entries with the same name? Normally, you should add the new file paths via the options: Add File, Add Folder, or AddPath*Wildcards. Then you will see the whitelisted entries as file/folder paths. You can edit the entry via the option Edit Info. Please note, that after doing it, the real path remains untouched - only the entry name will be different.

**Comment by AndyFul** [comment]
I will look at Restric&#39;tor in the morning. It is late here in Poland. Good night.:) 
            
          
     
      
       
        Dnia 4 marca 2020 00:20 Andreas Rehm &lt;notifications@github.com&gt; napisał(a):
       
    
       
         I&#39;m trying to migrate from Restric&#39;tor to H_C - Restric&#39;tor (maybe this should not be like this) creates entries without or even with the same name... 
 
 Hi sirrus,  
How do you add the entries with the same name? Normally, you should add the new file paths via the options: Add File, Add Folder, or AddPath*Wildcards. Then you will see the whitelisted entries as file/folder paths. You can edit the entry via the option Edit Info. Please note, that after doing it, the real path remains untouched - only the entry name will be different.

**Comment by AndyFul** [comment]
sirrus,
Restrictor is not compatible with H_C, so you cannot transfer the rules from Restrictor to H_C. 
In H_C, only user custom whitelisted entries can be edited (via "Edit Info" button). The H_C predefined whitelist rules (the entries which have the star in the beginning) cannot be edited.
The rules that you wanted to edit (multiple SRP rules with the same description) were probably added by H_C and not by Restrictor. For simplicity, H_C can display one predefined entry that contains several SRP rules.
