### ISSUE TITLE
WHITELIST

### ISSUE THREAD

**Issue by mnb21** [AndyFul/Hard_Configurator#20]
Hi,

~~Does `<Add Folder>` include all sub-folders and all files? For example, if I install MSYS2 in `C:\msys64` and add the path with `<Add Folder>`, I still have to add `C:\msys64\usr\bin\bash.exe` with `<Add File>` in order to use msys2/mingwXX.~~

Edit: I have blocked sponsor `bash.exe` - the reason for the above behavior.

I attached my config - [config.zip](https://github.com/AndyFul/Hard_Configurator/files/13837525/config.zip). I have only one user profile.

It seems the default deny config and whitelist isn't quite appropriate setup for environment where Visual Studio/Intel OneApi is used. I added to whitelist `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2022\Visual Studio Tools\VC` so I can use the MSVC tools with `x64 Native Tools Command Prompt for VS 2022`. Cmd window is opening but with the following `This program is blocked by group policy. For more information, contact your system administrator.
[vcvarsall.bat] Environment initialized for: 'x64'` When I check the log to see what is blocked - `Access to C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe has been restricted by your Administrator by location with policy rule {1016bbe0-a716-428b-822e-5e544b6a3100} placed on path powershell.exe.` If I run as Administrator `x64 Native Tools Command Prompt for VS 2022` everything seems ok. But I don't want to compile/build with Admin privileges. What would be your recommendation for such setup? A profile like `Windows_10_MT_Windows_Security_hardening.hdc`?

Edit: Above related - I have to remove `powershell.exe` and `reg.exe` from the blocked sponsors if I want to build as regular user (without admin privileges). Any way for example, to have blocked sponsor `powershell.exe` and run a `.bat` file that calls `powershell.exe` (whitelist ?)?

**Comment by AndyFul** [comment]
If you block powershell.exe via <Block Sponsors>, the powershell.exe is blocked by Path, and cannot be whitelisted.
Anyway, you can use a copy of the powershell.exe in another folder, and whitelist that path. Next, you can change the path of the powershell.exe called in your .bat file.

**Comment by mnb21** [comment]
Thanks for the idea.

I use unsigned exe files. These are in different places (different user spaces, system spaces) so I have to add them one by one to whitelist. Should I add them in one single place and add it to whitelist? What would be better in the context of security - one whitelist folder or multiple whitelist files/folders?

**Comment by AndyFul** [comment]
No one can probably answer such a question. We talk about very rare events of possible malware infections, and the differences in security are small. 
In theory, the safest method of whitelisting would be whitelisting files by hash. You can store the **copies of files** in one folder and whitelist them by hash. But, this would be probably very inconvenient.

**Comment by mnb21** [comment]
I see. Thanks again.
