### ISSUE TITLE
PowerShell FullLanguage Mode

### ISSUE THREAD

**Issue by lashoun** [AndyFul/Hard_Configurator#23]
Hi, HardConfigurator seems to make PowerShell sessions run in ConstrainedLanguage mode, but it interferes with my PowerShell profile with [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh). I get this error message:
```
Microsoft.PowerShell_profile.ps1: Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.
openssl_activate.ps1:
Line |
  10 |  . "C:\Users\-----\miniconda3\envs\default_conda\etc\conda\activate.d\ …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.
```

There is also an error related to the miniconda environment for Python.

Until now, I've always disabled SRPs when I needed to use the Terminal, but it's a bit of a hassle; is there a way to make stuff work without doing that every time? Either through exceptions (I tried whitelisting the two `.ps1` files but it didn't work, understandably) or by enabling FullLanguage mode? My threat model can allow that.

**Comment by AndyFul** [comment]
You can use Terminal (Admin).

**Comment by lashoun** [comment]
Yes, as I said in the previous message, I tried whitelisting, but I think the issue is that PowerShell is launched in ConstrainedLanguageMode. For instance, if I launch it with SRPs deactivated, everything is fine, and even if I reactivate SRPs, the PowerShell session still works fine. I tried tinkering with the `Block PowerShell Scripts` option but it didn't work either. The only fixes I've found are to switch off SRPs or changing the security level to `Unrestricted`, but it kind of beats the point of using HardConfigurator.

**Comment by AndyFul** [comment]
You probably whitelisted the wrong script. What Policy Scope do you use in SRP? Does Terminal (Admin) work with your scripts?

**Comment by lashoun** [comment]
I don't think so, but perhaps. I'm not sure what you mean by Policy Scope, sorry? Admin PowerShell does work, yes.

**Comment by AndyFul** [comment]
So, you use SRP in H_C to block processes running with standard rights. When using Terminal or PowerShell with Admin rights, SRP restrictions are bypassed, and PowerShell can run in Full Language Mode.
You can use <Tools> <Blocked Events / Security Logs> to see which PowerShell scripts should be whitelisted.

**Comment by lashoun** [comment]
That sounds about right, but there are no entries about PowerShell scripts when I launch PowerShell with standard rights.

**Comment by AndyFul** [comment]
If you run PowerShell code with errors from your first post and there are no entries (Event Id = 4100) in the FullEventLogView (executed via the option <Tools><Blocked Events / Security Logs>), then the blocked code is probably run directly from the Terminal or PowerShell console.  In such a case you cannot use whitelisting and the only method is running the Terminal or PowerShell with Admin rights.

**Comment by lashoun** [comment]
Fair enough, thanks for your help!
