### ISSUE TITLE
Blacklist / Autoblackliste user writeable folders

### ISSUE THREAD

**Issue by sirrus** [AndyFul/Hard_Configurator#3]
It would add additional securtiy if there is a Blacklist...

There are a lot of %windir% directories where users can write and execute...

It would be a great enhancement to have a blacklist an an auto add writeable (for everyone) folders automatically. (as it is in Restric'tor)

**Path examples:**
`C:\WINDOWS\debug\WIA
C:\WINDOWS\Hard_Configurator\Tools
C:\WINDOWS\Registration\CRMLog
C:\WINDOWS\servicing\Packages
C:\WINDOWS\servicing\Sessions
C:\WINDOWS\System32\Com\dmp
C:\WINDOWS\System32\FxsTmp
C:\WINDOWS\System32\spool\drivers\color
C:\WINDOWS\System32\spool\PRINTERS
C:\WINDOWS\System32\spool\SERVERS
C:\WINDOWS\System32\Tasks
C:\WINDOWS\System32\Tasks_Migrated
C:\WINDOWS\SysWOW64\Com\dmp
C:\WINDOWS\SysWOW64\FxsTmp
C:\WINDOWS\SysWOW64\Tasks
C:\WINDOWS\Tasks
C:\WINDOWS\Temp`

**Comment by AndyFul** [comment]
Hi,
I am not sure If I have understood you properly. These locations are already blacklisted by the H_C option <More SRP ...> <Protect Windows Folder>. You cannot run executables from them with standard rights.

**Comment by sirrus** [comment]
OK - got it (I havent read the help of the More SRP settings yet - sorry).
But What if i need to blacklist another folder - e.g. within ProgramFiles?

**Comment by AndyFul** [comment]
While creating H_C, I decided to skip user custom blacklisting to avoid problems. SRP uses a combination of Disallowed and Unrestricted rules which are not easy to understand for many users.    Regards  Andy 
            
          
     
      
       
        Dnia 4 marca 2020 00:07 Andreas Rehm &lt;notifications@github.com&gt; napisał(a):
       
    
       
         OK - got it (I havent read the help of the More SRP settings yet - sorry).  
But What if i need to blacklist another folder - e.g. within ProgramFiles?

**Comment by sirrus** [comment]
This makes sense - I'll evaluate and try to life your approach :-)

> While creating H_C, I decided to skip user custom blacklisting to avoid problems. SRP uses a combination of Disallowed and Unrestricted rules which are not easy to understand for many users.
