### ISSUE TITLE
Logoff not always necessary

### ISSUE THREAD

**Issue by sirrus** [AndyFul/Hard_Configurator#4]
Logoff is not alway necessary to activate SRP.
I would suggest to disable and enable SRP on applying changes - that usually does the job...

**Comment by beerisgood** [comment]
You can choice between logout and explorer refresh..

**Comment by sirrus** [comment]
@beerisgood I know - but Explorer Refresh is sometimes not working - "restarting" SRP works. Logoff is not necessary.

**Comment by AndyFul** [comment]
Hi,
Thanks for the suggestion. Do you mean using "(Re)Install SRP" and recover "Default Security Level"?
I will see if this can be a safe alternative to Logging OFF.

**Comment by sirrus** [comment]
I'm not sure how Restric'tor does it - it might be just setting unrestriced and setting the desired level again - but it does not need a logoff or explorer restart.

**Comment by AndyFul** [comment]
I am not sure how Restrictor can do it, but I found out how this can be easily done. Simply, adding/removing an extension on the Designated File Types list automatically applies changes in SRP restrictions. This is completely undocumented, so I have to test it thoroughly.
