### ISSUE TITLE
Adding EXE in release

### ISSUE THREAD

**Issue by michaelb-ae** [AndyFul/Hard_Configurator#6]
hello it would be nice to publish the exe in release like that we can watch for release only (for update), since we don't oppen it every day github will warn to go the hard configurator to do the update

Thanks

**Comment by AndyFul** [comment]
Hi,
I am not sure if I correctly understand you. Is not the Update button in H_C enough?

**Comment by michaelb-ae** [comment]
The problem (for me) is generally i install configure and forgot it but if there is an update i don't know since i don't open it often, and since i open GitHub every day it's for that i have asked to have the exe here but a command inserted in task manager to check once a week after update can do it too.

**Comment by AndyFul** [comment]
OK, I understand. The Hard_Configurator is a configuration tool - not a real time application. Any real-time protection comes from Windows built-in features. It is made to not call home, except when the user presses the Update button. I usually update it once or twice a year.

**Comment by michaelb-ae** [comment]
ok thanks for the answer
