### ISSUE TITLE
How to manually uninstall?

### ISSUE THREAD

**Issue by BlohoJo** [AndyFul/Hard_Configurator#8]
The program does not make an uninstaller.

There is an uninstall from the "Tools" button, but I don't fully understand this dialog:

![hardconfig](https://user-images.githubusercontent.com/8242464/101442108-9e0aad00-38e8-11eb-8f93-60807dd52115.png)

It seems to imply values will be overwritten with defaults if I click Yes.

I don't want anything whatsoever to be changed. I just want to uninstall Hard_Configurator.

Can I just delete the Hard_Configurator  directory in the Windows folder?

Are there any other directories, settings, or registry keys to get rid of?

**Comment by AndyFul** [comment]
Hard_Configurator (H_C) has got an uninstaller. After pressing the <Uninstall> button all H_C settings will be changed to Windows default values and all H_C files will be deleted.
You can delete the Hard_Configurator folder without uninstalling H_C (not recommended and unwise) but then all current restrictions (SRP, system hardening, Windows Defender settings, Windows Firewall policies) will be still active and you will not be able to change them or whitelist the blocked programs, scripts, other files blocked by SRP, and blocked outbound connections.

As you know, after initial configuration the H_C processes are not running in the system and all protection and restrictions come from Windows built-in features (SRP, Windows Policies, Firewall Policies, Windows Defender advanced settings). There is no advantage to deleting the H_C folder, except for a few MB of free space on the disk.

**Comment by BlohoJo** [comment]
OK, that's helpful, thanks very much! :wink:
